name: perfectmatch
description: Matches your name and that of your partner to see if they match
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  upgrader: ^8.3.0
  flutter_riverpod: ^2.4.8
  riverpod_annotation: ^2.2.1
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  mockito: ^5.4.2
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_annotation: ^2.2.1

flutter:

  uses-material-design: true
  assets:
   - assets/languages/
   - assets/images/
  #   - images/a_dot_ham.jpeg
